# DinD service is required for Testcontainers
services:
  - docker:dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: 'tcp://docker:2375'
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  # - lint
  - test
  - build

# lint:
#   stage: lint
#   image: node:20-alpine
#   script:
#     - yarn
#     - yarn lint

# format:
#   stage: lint
#   image: node:20-alpine
#   script:
#     - yarn
#     - yarn format:check

test:
  stage: test
  image: node:20-alpine
  script:
    - yarn
    - yarn test

build:
  stage: build
  image: node:20-alpine
  script:
    - yarn
    - yarn build

.node-cache:
  cache:
    key:
      files:
        - package.json
        - yarn.lock
    paths:
      - node_modules
