services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5

  update_db:
    build:
      context: .
      dockerfile: update_db.dockerfile
    environment:
      DATABASE_URL: 'postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB'
    depends_on:
      postgres:
        condition: service_healthy

  next:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: 'postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB'
      JWT_ACCESS_SECRET: 'secret_jwt'
      JWT_REFRESH_SECRET: 'secret_refresh'
      ACCESS_TOKEN_EXPIRES_MINUTES: 15
      REFRESH_TOKEN_EXPIRES_DAYS: 7
      WEBSITE_URL: 'http://localhost:3000'
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      update_db:
        condition: service_completed_successfully
