global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'next'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['next:3000']
      - labels:
          instance: 'next'
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
